version: '3.8'
services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    restart: always
    ports:
      - $PORT:$PORT
    depends_on:
      - nest-postgres
    env_file:
      - .env

  nest-postgres:
    image: postgres:15.1
    container_name: nest-postgres
    restart: always
    env_file:
      - .env
    volumes:
      - nest-postgres:/var/lib/postgresql/data

volumes:
  nest-postgres:
    name: nest-postgres-db
